spring:
  application:
    name: order-service
  main:
    web-application-type: servlet # WebFlux 대신 Servlet 사용
  cloud:
    loadbalancer:
      cache:
        ttl: 30s # 캐싱 유효 시간 설정
      configurations: weighted
      enabled: true

server:
  port: 19092 # 서버 포트

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/ # 유레카 클라이언트가 유레카 서버와 통신하는 URL

logging:
  level:
    org.springframework.cloud.loadbalancer: DEBUG