spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msa_exam_product
    username: msa_exam_product
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true