spring:
  application:
    name: server

server:
  port: 19090 # 서버 포트

eureka:
  client:
    register-with-eureka: false # 유레카 서버에 등록 여부 (유레카 서버는 false로 설정)
    fetch-registry: false       # 유레카 서버로부터 레지스트리 정보를 가져올지 여부 (유레카 서버는 false로 설정)
    service-url:
      defaultZone: http://127.0.0.1:19090/eureka/ # 유레카 클라이언트가 유레카 서버와 통신하는 URL
  instance:
    hostname: localhost # 호스트 이름 설정